# Generated by Django 6.0.1 on 2026-03-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modellar',
            new_name='Post',
        ),
    ]
